### PR TITLE
refactor(core): improve extensibility of `DiscussionPage`

### PR DESCRIPTION
**Pull request by DavideIadeluca**

### CODE REVIEW

**Review by imorland — APPROVED** [review]

**Comment by imorland** [comment]
Shouldn't we also add a hook so that we can insert Related Discussions via a new `ItemList` here? Don't we currently navigate the DOM for adding that?

**Comment by DavideIadeluca** [comment]
> Shouldn't we also add a hook so that we can insert Related Discussions via a new `ItemList` here? Don't we currently navigate the DOM for adding that?

The viewItems() method provides sufficient extensibility for third-party extensions. The remainder of the component is already quite extensible

**Comment by imorland** [comment]
> > Shouldn't we also add a hook so that we can insert Related Discussions via a new `ItemList` here? Don't we currently navigate the DOM for adding that?
> 
> The viewItems() method provides sufficient extensibility for third-party extensions. The remainder of the component is already quite extensible

Are you sure?
https://github.com/glowingblue/flarum-ext-related/blob/878e695ee4cfca5c908fb9e6055f3ea7827217d9/js/src/forum/addRelatedDiscussions.js#L49

**Comment by imorland** [comment]
Remember we want to avoid any DOM manipulation for the best compatibility...

**Comment by DavideIadeluca** [comment]
Yes, adding an item to `viewItems()` will work. It will be the exact same DOM in the end as right now, without requiring direct DOM manipulations.

**Pull request closed without merging**
